### ISSUE TITLE
SPA Mode

### ISSUE THREAD

**Issue by chrisreedio** [parallax/filament-syntax-entry#4]
Thanks for the awesome plugin/package! 
I had tried to make this a few times myself but it never looked as good or easy to use as yours! (Comments package is wonderful too!)

Anyway, This works great in normal mode but in SPA Mode, the syntax highlighting doesn't work when first loading the page.

If I refresh (F5 / Control+R) on the page where it isn't working then it works. 

Briefly looking through the code I'd suspect it has something to do with this part of the code not executing properly when the page (javascript) has already loaded on a previous page. 

https://github.com/parallax/filament-syntax-entry/blob/main/resources/js/index.js#L32

Not really sure the best way to fix though, but did want to report. Let me know if I can provide any more information to help. 

Thanks again!

**Comment by luke-parallax** [comment]
Resolved in the latest 2.x release!
