### ISSUE TITLE
Highlight not being installed

### ISSUE THREAD

**Issue by malle-pietje** [parallax/filament-syntax-entry#5]
When I add a json column to an Infolist Section,  the contents are simply rendered as text field. This is what I see:
![image](https://github.com/parallax/filament-syntax-entry/assets/12016131/cf27ec12-3ba0-4702-89c1-c7e542719573)

This how the entry is configured:
```php
                        Section::make('Full message details')
                            ->schema([
                                SyntaxEntry::make('full_msg')
                                    ->language('json')
                            ])
```
I also don't see any sign of Highlight.js in the node_modules directory.

What am I doing wrong?

**Comment by webnitros** [comment]
the package is not finished properly
you need to do some additional manipulation so that the variable with the language is transferred

the language variable is not involved anywhere

**Comment by webnitros** [comment]
modified the file to load on widgets

`resources/views/vendor/filament-syntax-entry/syntax-entry.blade.php`

replaced by
[resources/views/vendor/filament-syntax-entry/syntax-entry.blade.php](https://gist.github.com/webnitros/6e93179bb4f052ff1cbc976f2a24b102)

**Comment by malle-pietje** [comment]
Thanks, I already have pretty formatted json for regular text entries. Just looking to add highlighting, I’ll be creating my own custom component for this as soon as I have the time.
